export enum RarityTypes {
  COMMON = 'COMMON',
  RARE = 'RARE',
  EPIC = 'EPIC',
  LEGENDARY = 'LEGENDARY',
  UNKNOWN = 'UNKNOWN'
}

export const rarityHashMap = {
  'PINK': RarityTypes.COMMON,
  'CITRUS': RarityTypes.COMMON,
  'SKY': RarityTypes.COMMON,
  'SILVER ': RarityTypes.COMMON,
  'SILVER': RarityTypes.COMMON,
  'COBALT':RarityTypes.COMMON,
  'ROSEQUARTZ': RarityTypes.COMMON,
  'NUCLEAR': RarityTypes.COMMON,
  'OH': RarityTypes.COMMON,
  'CRYING': RarityTypes.COMMON,
  'ZEN': RarityTypes.COMMON,
  'GRATEFUL': RarityTypes.COMMON,
  'RECEIVER': RarityTypes.COMMON,
  'SPROUT': RarityTypes.COMMON,
  'ANTENNAE': RarityTypes.COMMON,
  'HANABI': RarityTypes.COMMON,
  'SCUFFED': RarityTypes.RARE,
  'ABUSED': RarityTypes.COMMON,
  'OCEAN': RarityTypes.RARE,
  'FRUIT': RarityTypes.RARE,
  'MIDNIGHT': RarityTypes.RARE,
  'COPPER': RarityTypes.RARE,
  'GOLD': RarityTypes.RARE,
  'RUSTY': RarityTypes.RARE,
  'AMETHYST': RarityTypes.RARE,
  'TITANIUM': RarityTypes.RARE,
  'SHORTCIRCUIT': RarityTypes.RARE,
  'WINKY': RarityTypes.RARE,
  'STARSTRUCK': RarityTypes.RARE,
  'GRILLS': RarityTypes.RARE,
  'PLASMA': RarityTypes.RARE,
  'DAISY': RarityTypes.RARE,
  'PRISTINE': RarityTypes.EPIC,
  'ENERGYSWORD': RarityTypes.RARE,
  'STABBED': RarityTypes.RARE,
  'GRAPH': RarityTypes.EPIC,
  'FUTURE': RarityTypes.EPIC,
  'ZWAVES': RarityTypes.EPIC,
  'INFRARED': RarityTypes.EPIC,
  'DIAMOND': RarityTypes.EPIC,
  'GRAPHITE': RarityTypes.EPIC,
  'RAINBOW': RarityTypes.EPIC,
  'TERMINATOR': RarityTypes.EPIC,
  'COOLCHAMELEON': RarityTypes.EPIC,
  'GUM': RarityTypes.EPIC,
  'BOT': RarityTypes.EPIC,
  'FRIEDEGG': RarityTypes.EPIC,
  'THENEST': RarityTypes.EPIC,
  'SOLSWORD': RarityTypes.EPIC,
  'FLAMECHAMELEON': RarityTypes.EPIC,
  'BABYBOT': RarityTypes.EPIC,
  'BABYBOTTRIPLETS': RarityTypes.LEGENDARY,
  'MATTE': RarityTypes.LEGENDARY,
  'BLACKONBLACK': RarityTypes.LEGENDARY,
  'CONSTELLATION':RarityTypes.LEGENDARY,
  'FUTUREWAVE': RarityTypes.LEGENDARY,
  'CRYSTALBLUE': RarityTypes.LEGENDARY,
  'CRYSTALRED': RarityTypes.LEGENDARY,
  'MATTEBLACK': RarityTypes.LEGENDARY,
  'CRYSTALYELLOW': RarityTypes.LEGENDARY,
  'CRYSTALWHITE': RarityTypes.LEGENDARY,
  'SCREENTIME': RarityTypes.LEGENDARY,
  'MECHAMASK': RarityTypes.LEGENDARY,
  'DOUBLECOOLCHAMELEON': RarityTypes.LEGENDARY,
  'GIGASTABBED': RarityTypes.LEGENDARY,
  'DOUBLEFLAMECHAMELEON': RarityTypes.LEGENDARY,
  'DOUBLEFROSTCHAMELEON': RarityTypes.LEGENDARY,
  'FROSTCHAMELEON': RarityTypes.EPIC,
  'SOLANA': RarityTypes.UNKNOWN,
  'MILKYWAY': RarityTypes.UNKNOWN,
  'ROVER': RarityTypes.UNKNOWN,
  'THECLAW': RarityTypes.UNKNOWN,
  'CUTE': RarityTypes.UNKNOWN,
  'IMMACULATE': RarityTypes.UNKNOWN,
  'PERFECTLYCRISPEDTOAST': RarityTypes.UNKNOWN,
  'CALMWATER': RarityTypes.UNKNOWN,
  'ZENGARDEN': RarityTypes.UNKNOWN,
  'SPOOKY': RarityTypes.UNKNOWN,
  'ZOMBIE': RarityTypes.UNKNOWN,
  'GIGAPLASMA': RarityTypes.UNKNOWN,
  'ALOT': RarityTypes.UNKNOWN,
  'NORMAL': RarityTypes.UNKNOWN,
  'PUZZLED': RarityTypes.UNKNOWN,
  'GRAPH PAPER': RarityTypes.UNKNOWN,
  'JUNGLE': RarityTypes.UNKNOWN,
  'CONCRETE JUNGLE': RarityTypes.UNKNOWN,
  'GARDEN': RarityTypes.UNKNOWN,
  'CRACKED': RarityTypes.UNKNOWN,
}

export const attributesArray = {
  background: ['Pink', 'Citrus', 'Sky', 'Ocean', 'Fruit', 'Midnight', 'Graph', 'Future', 'Z Waves', 'Infrared', 'Matte', 'Black on Black'],
  body: ['Silver', 'Cobalt', 'Rose Quartz', 'Nuclear', 'Copper', 'Gold', 'Rusty', 'Amethyst', 'Diamond', 'Graphite', 'Rainbow', 'Crystal Blue', 'Crystal Red', 'Crystal Yellow', 'Crystal White'],
  expression: ['!Oh','Crying', 'Zen', 'Grateful', 'Short Circuit', 'Winky', 'Star Stuck', 'Grills', 'Terminator', 'Gum', 'Bot', 'Screentime', 'Mecha Mask'],
  equipment: ['Receiver', 'Sprout', 'Antennae', 'Hanabi', 'None', 'Plasma', 'Daisy', 'Energy Sword', 'Fried Egg', 'The Nest', 'Cool Chameleon', 'Flame Chameleon', 'Double Cool Chameleon', 'Double Flame Chameleon', 'Sol Sword'],
  damage: ['Pristine', 'Scuffed', 'Abused', 'None']
}
